/*
 * 語聲山語 — 語言治療醫療院所資料集
 * 區域分類：北區(台北/新北/基隆/桃園/新竹) 中區(台中/苗栗/彰化/南投/雲林)
 *            南區(嘉義/台南/高雄/屏東/澎湖) 東區(宜蘭/花蓮/台東)
 *
 * 資料來源（公開資料）：
 *  - 臺北市療育院所名單（衛福部社家署發展遲緩兒童通報暨個案管理服務網 / 臺北市社會局）
 *  - 各院所官方網站、各縣市語言治療師公會公開名單
 * 院所資訊可能異動，就診前請先電話或上官網確認。
 *
 * 欄位：id, name, region, city, district, address, phone, url, services, dedicated
 *  - dedicated:true 代表「語言治療所」（以語言治療為主要服務的獨立治療所）
 *  - phone / url 可留空字串，頁面會顯示「—」或隱藏
 *
 * 要新增院所：在陣列中加一筆物件即可；目錄頁與各院所頁皆由此檔自動產生。
 */
window.CLINIC_DATA = [
  /* ===================== 北區 · 臺北市 ===================== */
  // 士林區
  {id:"yongxinshuo-shilin", name:"用心說語言治療所", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區中山北路五段811巷23號1樓", phone:"", url:"https://yourspeechclinic.tw", services:"全年齡語言／言語障礙評估、構音、口吃、吞嚥與嗓音治療", dedicated:true},
  {id:"nice-speech-shilin", name:"奈思語言治療所", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區中山北路五段685號10樓", phone:"0975-703478", url:"", services:"語言治療", dedicated:true},
  {id:"yongxinshuo-union-shilin", name:"用心說心理語言聯合治療所", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區福國路56巷17號1樓", phone:"0978-367671", url:"", services:"語言治療、心理治療", dedicated:true},
  {id:"pinheng-shilin", name:"天母品恆復健科診所", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區忠誠路一段137號", phone:"02-2838-6855", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"tpech-yangming-shilin", name:"臺北市立聯合醫院陽明院區", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區雨聲街105號", phone:"02-2835-3456#5187", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 北投區
  {id:"jia-speech-beitou", name:"家語言治療所", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區致遠一路二段107號", phone:"02-2821-7003", url:"", services:"語言治療", dedicated:true},
  {id:"shihe-beitou", name:"石牌實和復健科診所", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區文林北路262號1樓", phone:"02-2827-3255", url:"", services:"職能、語言治療", dedicated:false},
  {id:"xukang-beitou", name:"旭康診所", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區石牌路一段40號", phone:"02-2828-0067", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"guandu-hosp-beitou", name:"臺北市立關渡醫院", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區知行路225巷12號", phone:"02-2858-7140", url:"", services:"職能、語言、心理治療", dedicated:false},
  // 大同區
  {id:"tpech-zhongxing-datong", name:"臺北市立聯合醫院中興院區兒童發展評估中心", region:"north", city:"臺北市", district:"大同區", address:"臺北市大同區鄭州路145號1-2樓", phone:"02-2555-3000#2855", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  // 中山區
  {id:"xiangxiang-zhongshan", name:"響響語言治療所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區吉林路236巷5號", phone:"02-2581-0992", url:"", services:"語言治療", dedicated:true},
  {id:"forest-speech-zhongshan", name:"森林語言治療所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區民生西路16號5樓", phone:"02-2523-9411", url:"", services:"語言治療", dedicated:true},
  {id:"tongle-zhongshan", name:"童樂語言治療所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區撫順街41巷1-6號", phone:"0919-371691", url:"", services:"語言治療", dedicated:true},
  {id:"shikang-zhongshan", name:"中山適康復健科診所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區龍江路268號2樓-1", phone:"02-2515-5150", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"mackay-taipei-zhongshan", name:"馬偕紀念醫院（台北院區）", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區中山北路二段92號", phone:"02-2543-3535#3051", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 中正區
  {id:"langlang-zhongzheng", name:"朗朗語言治療所", region:"north", city:"臺北市", district:"中正區", address:"臺北市中正區忠孝西路一段45號11樓-4", phone:"0935-919971", url:"", services:"語言治療", dedicated:true},
  {id:"ntuh-zhongzheng", name:"國立臺灣大學醫學院附設醫院", region:"north", city:"臺北市", district:"中正區", address:"臺北市中正區中山南路8號", phone:"02-2312-3456#70401", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"tpech-heping-zhongzheng", name:"臺北市立聯合醫院和平院區", region:"north", city:"臺北市", district:"中正區", address:"臺北市中正區中華路二段33號", phone:"02-2388-9595#8001", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"guting-shikang-zhongzheng", name:"古亭適康復健科診所", region:"north", city:"臺北市", district:"中正區", address:"臺北市中正區南昌路二段200號1-2樓", phone:"02-2367-5885", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 萬華區
  {id:"pengling-wanhua", name:"彭聆語言治療所", region:"north", city:"臺北市", district:"萬華區", address:"臺北市萬華區中華路一段16號9樓之3", phone:"02-2388-0648", url:"https://www.pengling.com.tw", services:"語言障礙、發展遲緩、自閉症、溝通障礙評估與治療", dedicated:true},
  // 大安區
  {id:"dabu-daan", name:"大步語言治療所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區仁愛路四段122巷63號6樓-2", phone:"0978-703327", url:"", services:"語言治療", dedicated:true},
  {id:"mengyu-daan", name:"萌語語言治療所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區信義路四段58號8樓-6", phone:"02-2700-0700", url:"", services:"語言治療", dedicated:true},
  {id:"tpech-renai-daan", name:"臺北市立聯合醫院仁愛院區", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區仁愛路四段10號", phone:"02-2709-3600#3126", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"cathay-daan", name:"國泰綜合醫院", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區仁愛路四段280號", phone:"02-2708-2121#3579", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"hungen-daan", name:"宏恩綜合醫院", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區仁愛路四段61號", phone:"02-2771-3161#835", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"shijian-daan", name:"適健復健科診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區忠孝東路四段166號8樓", phone:"02-8771-7039", url:"", services:"職能、語言治療", dedicated:false},
  {id:"xingcheng-daan", name:"杏誠復健診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區信義路四段173號2樓", phone:"02-2706-1732", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yongcheng-daan", name:"永誠復健科診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區復興南路二段236號2樓", phone:"02-2707-1608", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"daren-daan", name:"達仁診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區信義路二段208號4樓", phone:"02-2394-0006", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"rensheng-daan", name:"仁生復健科診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區信義路四段265巷17號1-2樓", phone:"02-2703-0336", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shiqun-daan", name:"適群診所", region:"north", city:"臺北市", district:"大安區", address:"臺北市大安區四維路198巷32號", phone:"02-2755-3700", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 信義區
  {id:"sibi-xinyi", name:"思比語言治療所", region:"north", city:"臺北市", district:"信義區", address:"臺北市信義區忠孝東路五段412號11樓之3", phone:"0963-510158", url:"https://www.spspeechclinic.com", services:"兒童語言治療、吞嚥治療、嗓音治療、社交互動團體、到府居家治療", dedicated:true},
  {id:"yuanli-xinyi", name:"原力復健科診所", region:"north", city:"臺北市", district:"信義區", address:"臺北市信義區基隆路二段145號B1-2樓", phone:"02-2732-7091", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"tmuh-xinyi", name:"臺北醫學大學附設醫院", region:"north", city:"臺北市", district:"信義區", address:"臺北市信義區吳興街252號", phone:"02-2737-2181#1241", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 文山區
  {id:"jiamei-wenshan", name:"嘉美言語語言治療所", region:"north", city:"臺北市", district:"文山區", address:"臺北市文山區興隆路三段152巷16號1樓", phone:"0981-176931", url:"", services:"語言治療", dedicated:true},
  {id:"wanfang-wenshan", name:"臺北市立萬芳醫院", region:"north", city:"臺北市", district:"文山區", address:"臺北市文山區興隆路三段111號", phone:"02-2930-7930#1802", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 松山區
  {id:"taan-hosp-songshan", name:"臺安醫院", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區八德路二段424號", phone:"02-2771-8151#2595", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"zhengfeng-songshan", name:"正風復健科診所", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區光復北路135號1樓", phone:"02-2760-2666", url:"", services:"職能、語言治療", dedicated:false},
  {id:"changgung-taipei-songshan", name:"臺北長庚紀念醫院", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區敦化北路199號", phone:"02-3281-2200#8148", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 南港區
  {id:"tpech-zhongxiao-nangang", name:"臺北市立聯合醫院忠孝院區", region:"north", city:"臺北市", district:"南港區", address:"臺北市南港區同德路87號", phone:"02-2786-1288#8084", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"kaixin-nangang", name:"開馨診所", region:"north", city:"臺北市", district:"南港區", address:"臺北市南港區南港路二段38巷6-1號1樓", phone:"02-2653-2987", url:"", services:"職能、語言、心理治療", dedicated:false},
  // 內湖區
  {id:"neihu-speech", name:"內湖語言治療所", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區民權東路六段266號9樓", phone:"0938-508627", url:"", services:"語言治療", dedicated:true},
  {id:"tsgh-neihu", name:"三軍總醫院", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區成功路二段325號", phone:"02-8792-3311#10406", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"hengxin-neihu", name:"內湖恆新復健科診所", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區瑞光路337號7樓", phone:"02-2627-8666", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"likang-neihu", name:"力康復健科診所", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區內湖路一段358號2樓", phone:"02-2658-0866", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shikang-neihu", name:"適康復健科診所", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區文德路141、143號", phone:"02-8797-7566", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"cathay-neihu", name:"國泰內湖診所", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區瑞光路337號C棟1-4樓", phone:"02-8797-2121", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"cmuh-taipei-neihu", name:"中國醫藥大學附設醫院臺北分院", region:"north", city:"臺北市", district:"內湖區", address:"臺北市內湖區內湖路二段360號", phone:"02-2791-9696#2004", url:"https://www.cmuh.cmu.edu.tw", services:"物理、職能、語言治療", dedicated:false},
  // 松山區（續）
  {id:"kangjian-songshan", name:"康健診所", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區延吉街11號2樓", phone:"02-2577-9682", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"hopu-songshan", name:"荷普職能治療所", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區敦化北路114、116號2樓", phone:"02-2547-2315", url:"", services:"職能、語言治療", dedicated:false},
  {id:"youshi-songshan", name:"悠適復健科診所", region:"north", city:"臺北市", district:"松山區", address:"臺北市松山區光復北路11巷65、67號", phone:"02-2749-3088", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  // 中山區（續）
  {id:"chengan-zhongshan", name:"承安診所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區民生東路三段90號", phone:"02-2503-2633", url:"", services:"職能、語言治療", dedicated:false},
  {id:"aidile-zhongshan", name:"愛迪樂治療所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區民生東路二段127巷19號", phone:"02-2521-6043", url:"", services:"職能、語言治療", dedicated:false},
  {id:"boshi-zhongshan", name:"博士聽力所", region:"north", city:"臺北市", district:"中山區", address:"臺北市中山區復興北路164號7樓之1", phone:"02-2718-5125", url:"", services:"聽力檢查、語言治療", dedicated:false},
  // 文山區（續）
  {id:"wanlong-likang-wenshan", name:"萬隆力康診所", region:"north", city:"臺北市", district:"文山區", address:"臺北市文山區羅斯福路五段127號2樓", phone:"02-8931-9799", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 北投區（續）
  {id:"vghtpe-beitou", name:"臺北榮民總醫院", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區石牌路二段201號", phone:"02-2871-2121#2940", url:"https://www.vghtpe.gov.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"chenghsin-beitou", name:"振興醫療財團法人振興醫院", region:"north", city:"臺北市", district:"北投區", address:"臺北市北投區振興街45號", phone:"02-2826-4400#3807", url:"https://www.chgh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  // 士林區（續）
  {id:"shinkong-shilin", name:"新光吳火獅紀念醫院", region:"north", city:"臺北市", district:"士林區", address:"臺北市士林區文昌路95號", phone:"02-2833-2211#2531", url:"https://www.skh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},

  /* ----- 北區 · 新北市 ----- */
  {id:"zhenhao-banqiao", name:"真好語言治療所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區自由路17巷11號", phone:"02-2256-1755", url:"", services:"語言治療", dedicated:true},
  {id:"ling-speech-banqiao", name:"聆語言治療所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區中山路一段1號9樓之25", phone:"02-8964-6318", url:"", services:"語言治療", dedicated:true},
  {id:"haoshiguang-banqiao", name:"好蒔光職能語言治療所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區光正街45巷18號", phone:"02-2271-0954", url:"", services:"職能、語言治療", dedicated:true},
  {id:"xingyu-banqiao", name:"星嶼心理語言職能聯合治療所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區文化路一段165號6樓之5", phone:"02-2969-9307", url:"", services:"職能、語言、心理治療", dedicated:true},
  {id:"femh-banqiao", name:"亞東紀念醫院", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區南雅南路二段21號", phone:"02-7728-2297", url:"https://www.femh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"xinzhuang-zhenhao", name:"新莊真好語言治療所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區明中街40號1樓", phone:"02-2996-1755", url:"", services:"語言治療", dedicated:true},
  {id:"botao-xinzhuang", name:"博淘語言治療所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區新泰路136號3樓", phone:"02-2277-5588", url:"", services:"語言治療（採預約制）", dedicated:true},
  {id:"xiaoyi-xinzhuang", name:"曉依語言治療所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區中央路303號3樓", phone:"0922-024698", url:"https://www.hsiaoyist.com", services:"語言治療（採預約制）", dedicated:true},
  {id:"tph-xinzhuang", name:"衛生福利部臺北醫院", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區思源路127號", phone:"02-2276-5566#1106", url:"https://www.tph.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinyu-zhonghe", name:"心語語言治療所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區新生街30巷30號1樓", phone:"0968-101568", url:"", services:"語言治療", dedicated:true},
  {id:"taotao-zhonghe", name:"滔滔語言治療所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區景平路385巷10號1樓", phone:"0912-616583", url:"", services:"語言治療", dedicated:true},
  {id:"shuanghe-zhonghe", name:"衛生福利部雙和醫院", region:"north", city:"新北市", district:"中和區", address:"新北市中和區中正路291號", phone:"02-2249-0088#2959", url:"https://www.shh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"yaya-yonghe", name:"芽芽語言治療所", region:"north", city:"新北市", district:"永和區", address:"新北市永和區中和路421巷16弄7號", phone:"02-2929-2092", url:"", services:"語言治療", dedicated:true},
  {id:"bitan-xindian", name:"新店必談語言治療所", region:"north", city:"新北市", district:"新店區", address:"新北市新店區文化路75巷7號1樓", phone:"0918-600736", url:"", services:"語言治療（採預約制）", dedicated:true},
  {id:"cardinal-xindian", name:"天主教耕莘醫院", region:"north", city:"新北市", district:"新店區", address:"新北市新店區中正路362號", phone:"02-2219-3391#67401", url:"https://www.cth.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"tcmg-xindian", name:"台北慈濟醫院", region:"north", city:"新北市", district:"新店區", address:"新北市新店區建國路289號", phone:"02-6628-9779#7713", url:"https://taipei.tzuchi.com.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"tamsui-mackay", name:"淡水馬偕紀念醫院", region:"north", city:"新北市", district:"淡水區", address:"新北市淡水區民生路45號", phone:"02-2809-4661#2200", url:"https://www.mmh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"lvyou-taishan", name:"綠柚語言治療所", region:"north", city:"新北市", district:"泰山區", address:"新北市泰山區仁愛路100巷58號1樓", phone:"02-2900-1106", url:"", services:"語言治療", dedicated:true},
  {id:"linkou-anxin", name:"霖口安心語言治療所", region:"north", city:"新北市", district:"林口區", address:"新北市林口區民族路69號1樓", phone:"02-6604-0368", url:"", services:"職能、語言治療", dedicated:true},
  {id:"ntuh-jinshan", name:"臺大醫院金山分院", region:"north", city:"新北市", district:"金山區", address:"新北市金山區五湖里玉爐路7號", phone:"02-2498-9898#1201", url:"https://www.hch.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"banying-banqiao", name:"板英醫院", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區文化路一段269號", phone:"02-8251-3923#218", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"entian-banqiao", name:"恩典復健家醫科診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區文化路二段155號", phone:"02-2255-1661", url:"", services:"職能、語言治療", dedicated:false},
  {id:"jiayi-banqiao", name:"佳醫診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區忠孝路88號", phone:"02-2956-2780", url:"", services:"職能、語言治療", dedicated:false},
  {id:"nthcm-banqiao", name:"新北市立聯合醫院（板橋院區）", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區英士路198號", phone:"02-2257-5151#3500", url:"https://www.nthcm.ntpc.gov.tw", services:"語言、心理治療", dedicated:false},
  {id:"changhong-banqiao", name:"昌弘復健科診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區中正路194號", phone:"02-2966-0066", url:"", services:"職能、語言治療", dedicated:false},
  {id:"heqian-banqiao", name:"和謙診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區民權路214號1樓", phone:"02-2968-0090", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"daxin-banqiao", name:"大新復健科診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區篤行路一段31號", phone:"02-8687-2626", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"banxin-banqiao", name:"板新醫院", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區中正路189號", phone:"02-2960-9955#202", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"chenyuan-banqiao", name:"辰元復健科診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區雙十路三段31號2樓", phone:"02-2258-2299", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jianxin-banqiao", name:"健心復健科診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區重慶路201號", phone:"02-8961-2888", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"kangting-banqiao", name:"康庭診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區四川路一段150號、152號", phone:"02-2951-2250", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jinjiankang-banqiao", name:"金健康診所", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區貴興路100號1樓及地下一層", phone:"02-2958-7666#201", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"cathay-banqiao", name:"板橋國泰醫院", region:"north", city:"新北市", district:"板橋區", address:"新北市板橋區忠孝路5號", phone:"02-2958-3333", url:"https://www.cgh.org.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"cathay-xizhi", name:"汐止國泰綜合醫院", region:"north", city:"新北市", district:"汐止區", address:"新北市汐止區建成路59巷2號", phone:"02-2648-2121#3611", url:"https://www.cgh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"fukang-yonghe", name:"永和復康醫院", region:"north", city:"新北市", district:"永和區", address:"新北市永和區中和路575號", phone:"02-2924-0925", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"cardinal-yonghe", name:"天主教耕莘醫院（永和分院）", region:"north", city:"新北市", district:"永和區", address:"新北市永和區中興街80號", phone:"02-2925-1302", url:"https://www.cth.org.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"jingai-yonghe", name:"景愛復健科診所", region:"north", city:"新北市", district:"永和區", address:"新北市永和區中正路46號", phone:"02-8668-3188", url:"", services:"職能、語言治療", dedicated:false},
  {id:"yongxin-yonghe", name:"永馨復健診所", region:"north", city:"新北市", district:"永和區", address:"新北市永和區竹林路139號1～4樓、141號1～3樓", phone:"02-8926-9666", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yihe-zhonghe", name:"怡和醫院", region:"north", city:"新北市", district:"中和區", address:"新北市中和區連城路49號", phone:"02-2245-0009#9", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"jianan-zhonghe", name:"佳南診所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區景新街431號1樓", phone:"02-2940-8358", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xionghe-zhonghe", name:"雄鶴診所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區漢民路404號", phone:"02-2228-1280", url:"", services:"職能、語言治療", dedicated:false},
  {id:"kangyou-zhonghe", name:"康祐診所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區中山路三段121號1樓、121之1號2樓、3樓", phone:"02-2223-9293#23", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"suian-zhonghe", name:"穗安復健科診所", region:"north", city:"新北市", district:"中和區", address:"新北市中和區民樂路36號1樓", phone:"02-2223-2187", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"enhua-tucheng", name:"恩樺醫院", region:"north", city:"新北市", district:"土城區", address:"新北市土城區中央路一段7～18號", phone:"02-2263-9955#6006", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"suicheng-tucheng", name:"穗城復健科診所", region:"north", city:"新北市", district:"土城區", address:"新北市土城區金城路三段176號", phone:"02-8273-2239", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"enzhugong-sanxia", name:"恩主公醫院", region:"north", city:"新北市", district:"三峽區", address:"新北市三峽區中山路198號3樓", phone:"02-2672-3456#3303", url:"https://www.eskh.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"yongfeng-shulin", name:"永峰診所", region:"north", city:"新北市", district:"樹林區", address:"新北市樹林區中山路一段177之1號", phone:"02-2681-3002", url:"", services:"職能、語言治療", dedicated:false},
  {id:"yangsheng-shulin", name:"揚昇診所", region:"north", city:"新北市", district:"樹林區", address:"新北市樹林區太元街21號1樓", phone:"02-8686-9771", url:"", services:"職能、語言治療", dedicated:false},
  {id:"chengyang-shulin", name:"誠陽復健科診所", region:"north", city:"新北市", district:"樹林區", address:"新北市樹林區東華街85號1樓", phone:"02-8685-2806", url:"", services:"職能、語言治療", dedicated:false},
  {id:"chengxin-yingge", name:"澄欣復健科診所", region:"north", city:"新北市", district:"鶯歌區", address:"新北市鶯歌區國慶街136號、140號、142號1樓", phone:"02-2678-0055", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"nthcm-sanchong", name:"新北市立聯合醫院（三重院區）", region:"north", city:"新北市", district:"三重區", address:"新北市三重區新北大道一段3號", phone:"02-2982-9111#3500", url:"https://www.nthcm.ntpc.gov.tw", services:"物理、職能、語言、心理治療、親子治療", dedicated:false},
  {id:"youmin-sanchong", name:"祐民醫院", region:"north", city:"新北市", district:"三重區", address:"新北市三重區重新路二段2號", phone:"02-2978-3456#2933", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"hongren-sanchong", name:"宏仁醫院", region:"north", city:"新北市", district:"三重區", address:"新北市三重區三和路二段186號", phone:"02-2978-4022", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shengfeng-xinzhuang", name:"盛豐診所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區後港一路29號2樓", phone:"02-2206-2339", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"lesheng-xinzhuang", name:"衛生福利部樂生療養院（樂生院區）", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區中正路794號", phone:"02-8200-6600#2247", url:"https://www.lslp.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"xintai-xinzhuang", name:"新泰綜合醫院", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區新樹路176號", phone:"02-2996-2121#5803", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinzhuang-shihe", name:"新莊實和復健診所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區昌隆街23號1樓", phone:"02-2276-6200#15", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yuanhua-xinzhuang", name:"原華診所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區新泰路128號", phone:"02-2277-2087#15", url:"", services:"職能、語言治療", dedicated:false},
  {id:"xinren-xinzhuang", name:"新仁醫院", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區中正路395號", phone:"02-2201-7212#228", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shibo-xinzhuang", name:"世博診所", region:"north", city:"新北市", district:"新莊區", address:"新北市新莊區新泰路134號1樓", phone:"02-8993-1518", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"fju-taishan", name:"天主教輔仁大學附設醫院", region:"north", city:"新北市", district:"泰山區", address:"新北市泰山區貴子路69號", phone:"02-8512-8888#21020", url:"https://www.fjuh.fju.edu.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"luzhou-shihe", name:"蘆洲實和復健診所", region:"north", city:"新北市", district:"蘆洲區", address:"新北市蘆洲區長榮路156號1樓", phone:"02-8286-9320#15", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yuansheng-luzhou", name:"沅昇復健科診所", region:"north", city:"新北市", district:"蘆洲區", address:"新北市蘆洲區復興路87巷6號", phone:"02-8285-6259", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shikang-tamsui", name:"實康復健科診所", region:"north", city:"新北市", district:"淡水區", address:"新北市淡水區學府路36號2樓", phone:"02-2629-2000", url:"", services:"物理、職能、語言治療", dedicated:false},

  /* ----- 北區 · 桃園市 ----- */
  {id:"wenren-taoyuan", name:"文仁語言治療所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區秀山路3號", phone:"03-339-1780", url:"http://www.wenren.com.tw", services:"語言治療", dedicated:true},
  {id:"guanjian-zhongli", name:"關鍵語言治療所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區台貿二街92號", phone:"03-436-4329", url:"", services:"語言治療", dedicated:true},
  {id:"lilun-zhongli", name:"立倫診所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區中央西路二段208號", phone:"03-495-3287", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"tiansheng-zhongli", name:"天晟醫院", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區延平路155號", phone:"03-462-9292#22211", url:"https://www.tcmg.com.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"tygh-taoyuan", name:"衛生福利部桃園醫院", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區中山路1492號", phone:"03-369-9721", url:"https://www.tygh.mohw.gov.tw", services:"兒童語言治療（復健科）", dedicated:false},

  /* ----- 北區 · 新竹市 ----- */
  {id:"soundwell-hsinchu", name:"悅聲語言治療所", region:"north", city:"新竹市", district:"北區", address:"新竹市北區湳中街42號", phone:"03-531-3895", url:"https://soundwell.com.tw", services:"語言治療（新竹縣市第一家語言治療所，採預約自費）", dedicated:true},
  {id:"suntalk-hsinchu", name:"小太陽語言治療所", region:"north", city:"新竹市", district:"北區", address:"新竹市北區民族路55-1號2、3樓", phone:"03-526-6910", url:"", services:"語言治療", dedicated:true},
  {id:"yuhe-hsinchu", name:"語禾語言治療所", region:"north", city:"新竹市", district:"香山區", address:"新竹市金城三路121號1樓", phone:"0921-631062", url:"https://sites.google.com/view/yh-speech", services:"語言治療", dedicated:true},
  {id:"chenjing-hsinchu", name:"晨境語言治療所", region:"north", city:"新竹市", district:"北區", address:"新竹市北區北大路180號4樓之1", phone:"0921-569487", url:"", services:"語言治療", dedicated:true},
  {id:"yuji-hsinchu", name:"宇治太太語言治療所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區湳雅街126巷24號1樓", phone:"0986-861580", url:"", services:"語言治療", dedicated:true},
  {id:"xinyan-hsinchu", name:"欣言語言治療所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區食品路260巷7號1樓", phone:"", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"yujilaoye-hsinchu", name:"宇治老爺語言治療所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區光復路一段268巷12號", phone:"0979-581580", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"erle-hsinchu", name:"兒樂語言治療所", region:"north", city:"新竹市", district:"北區", address:"新竹市北區中和路26號3樓", phone:"0919-239526", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"ntuh-hsinchu", name:"臺大醫院新竹分院", region:"north", city:"新竹市", district:"東區", address:"新竹市東區經國路一段442巷25號", phone:"03-532-6151", url:"https://www.hch.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"mackay-hsinchu", name:"新竹馬偕紀念醫院", region:"north", city:"新竹市", district:"東區", address:"新竹市東區光復路二段690號", phone:"03-611-9595", url:"https://www.hc.mmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"mackay-child-hsinchu", name:"新竹馬偕兒童醫院", region:"north", city:"新竹市", district:"東區", address:"新竹市東區建功二路28號", phone:"03-611-9595", url:"https://www.hc.mmh.org.tw", services:"兒童復健、語言治療", dedicated:false},
  {id:"cathay-hsinchu", name:"新竹國泰綜合醫院", region:"north", city:"新竹市", district:"北區", address:"新竹市北區中華路二段678號", phone:"03-527-8999", url:"https://www.cgh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"afmh-hsinchu", name:"國軍新竹地區醫院", region:"north", city:"新竹市", district:"北區", address:"新竹市北區武陵路3號", phone:"03-539-9520", url:"", services:"復健科語言治療", dedicated:false},
  {id:"guanhongchang-hsinchu", name:"關弘昌復健科診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區北大路32號", phone:"03-534-0860", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yuzheng-hsinchu", name:"余鄭錦峰復健診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區南門街22號", phone:"03-522-3339", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinchao-hsinchu", name:"新朝診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區林森路299號", phone:"03-526-1718", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"anhe-hsinchu", name:"安禾診所", region:"north", city:"新竹市", district:"北區", address:"新竹市北區經國路一段379巷8號", phone:"03-535-3336", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"hengxin-hsinchu", name:"恆心診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區關新路225號5樓", phone:"03-666-1766", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"chenxin-hsinchu", name:"宸新復健科診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區光復路一段371號B1", phone:"03-564-7999", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yunxin-hsinchu", name:"耘新復健診所", region:"north", city:"新竹市", district:"東區", address:"新竹市東區民生路193號1F、B1", phone:"03-533-9666", url:"", services:"物理、職能、語言治療", dedicated:false},

  /* ----- 北區 · 基隆市 ----- */
  {id:"cgmh-keelung", name:"基隆長庚紀念醫院（情人湖院區）", region:"north", city:"基隆市", district:"安樂區", address:"基隆市安樂區基金一路208巷200號", phone:"02-2431-3131#2414", url:"https://www.cgmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"kln-keelung", name:"衛生福利部基隆醫院", region:"north", city:"基隆市", district:"信義區", address:"基隆市信義區信二路268號", phone:"02-2429-2525#3518", url:"https://www.kln.mohw.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"huian-keelung", name:"惠安復健科診所", region:"north", city:"基隆市", district:"七堵區", address:"基隆市七堵區南興路10、12號2樓", phone:"02-2456-9908", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"keelung-child-speech", name:"基隆市兒童語言治療中心", region:"north", city:"基隆市", district:"中正區", address:"基隆市中正區中正路236號2樓", phone:"02-2463-1198", url:"", services:"兒童語言治療（公費，需預約）", dedicated:false},
  {id:"yuguo-keelung", name:"語果語言治療所", region:"north", city:"基隆市", district:"仁愛區", address:"基隆市仁愛區仁二路95號8樓", phone:"0938-097861", url:"", services:"語言治療（採預約制）", dedicated:true},
  {id:"renxiang-keelung", name:"仁祥診所", region:"north", city:"基隆市", district:"仁愛區", address:"基隆市仁愛區忠一路20號", phone:"02-2423-2111#3001", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"minerhosp-keelung", name:"臺灣礦工醫院", region:"north", city:"基隆市", district:"暖暖區", address:"基隆市暖暖區源遠路29號", phone:"02-2457-9101#229", url:"", services:"物理、職能、語言治療", dedicated:false},

  /* ----- 北區 · 桃園市（續） ----- */
  {id:"qingpu-speech-zhongli", name:"青埔語言治療所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區青峰路一段41號12樓", phone:"", url:"", services:"語言治療", dedicated:true},
  {id:"yanxin-zhongli", name:"言心語言治療所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區環中東路842-1號3樓", phone:"0910-937231", url:"https://yanxinspeech.com", services:"兒童／成人語言治療、構音、吞嚥、嗓音", dedicated:true},
  {id:"yufu-speech-taoyuan", name:"羽賦語言治療所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區南平路421號5樓", phone:"0906-597982", url:"", services:"語言治療", dedicated:true},
  {id:"linkou-cgmh-guishan", name:"林口長庚紀念醫院", region:"north", city:"桃園市", district:"龜山區", address:"桃園市龜山區復興街5號", phone:"03-328-1200#8147", url:"https://www.cgmh.org.tw", services:"復健科語言治療、早期療育", dedicated:false},
  {id:"taoyuan-cgmh-guishan", name:"桃園長庚紀念醫院", region:"north", city:"桃園市", district:"龜山區", address:"桃園市龜山區頂湖路123號", phone:"03-319-6200#2371", url:"https://www.cgmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"lianxin-pingzhen", name:"聯新國際醫院", region:"north", city:"桃園市", district:"平鎮區", address:"桃園市平鎮區廣泰路77號", phone:"03-494-1234", url:"https://www.landseedhospital.com.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"stpaul-taoyuan", name:"天主教聖保祿醫院", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區建新街123號", phone:"03-361-3141", url:"https://www.stpaul.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"minsheng-taoyuan", name:"敏盛綜合醫院（三民院區）", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區三民路三段106號", phone:"03-337-9340", url:"https://www.e-ms.com.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"changrong-zhongli", name:"中壢長榮醫院", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區環中東路150號", phone:"03-463-1230#5121", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"huayang-zhongli", name:"華揚醫院", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區中北路二段316號6樓", phone:"03-457-7200#0605", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"lianxin-clinic-zhongli", name:"聯新診所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區福州路21號", phone:"03-437-9595#201", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"zhongmei-zhongli", name:"中美醫院", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區中美路95號", phone:"03-426-6222", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"changshen-zhongli", name:"長慎醫院", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區中山東路二段525號", phone:"03-456-9779", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"kangze-zhongli", name:"康澤復健科診所", region:"north", city:"桃園市", district:"中壢區", address:"桃園市中壢區信義路83號", phone:"03-271-6129", url:"", services:"職能、物理、語言治療", dedicated:false},
  {id:"taoxin-taoyuan", name:"桃新醫院（聯新桃新分院）", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區復興路195號", phone:"03-332-5678#1218", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"hengxin-taoyuan", name:"恆新復健科診所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區新埔八街111號", phone:"03-325-7878", url:"", services:"物理、職能、語言、心理治療（自費）", dedicated:false},
  {id:"deren-taoyuan", name:"德仁醫院", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區桃鶯路245號", phone:"03-361-7985", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"zhensheng-taoyuan", name:"振生醫院", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區三民路二段288號4樓", phone:"03-335-6156#400", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ymrehab-taoyuan", name:"陽明復健專科診所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區金門二街296號", phone:"03-377-7891", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"liyucheng-taoyuan", name:"李裕承復健科診所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區中山路810號", phone:"03-369-1191", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"liangqi-taoyuan", name:"良祺復健診所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區南平路516、518號2樓", phone:"03-346-7899", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"youershi-taoyuan", name:"優兒適職能治療所", region:"north", city:"桃園市", district:"桃園區", address:"桃園市桃園區復興路389號3樓", phone:"03-331-8899", url:"", services:"職能、語言、物理、心理治療", dedicated:false},
  {id:"tiancheng-yangmei", name:"天成醫院", region:"north", city:"桃園市", district:"楊梅區", address:"桃園市楊梅區新成路196號", phone:"03-478-2350#62211", url:"", services:"物理、職能、語言治療、認知訓練", dedicated:false},
  {id:"ruixi-yangmei", name:"瑞溪復健科診所", region:"north", city:"桃園市", district:"楊梅區", address:"桃園市楊梅區瑞溪路二段189號1樓至4樓", phone:"03-482-0343", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"lesheng-guishan", name:"衛生福利部樂生療養院（迴龍院區）", region:"north", city:"桃園市", district:"龜山區", address:"桃園市龜山區萬壽路一段50巷2號", phone:"02-8200-6600#2240", url:"https://www.lslp.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"daming-guishan", name:"大明醫院", region:"north", city:"桃園市", district:"龜山區", address:"桃園市龜山區萬壽路二段964號", phone:"03-350-5092", url:"", services:"物理、職能、語言、聽語治療", dedicated:false},
  {id:"xukang-luzhu", name:"旭康診所", region:"north", city:"桃園市", district:"蘆竹區", address:"桃園市蘆竹區中山路52-1號1樓、56號1樓", phone:"03-312-9011", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shangdaxin-luzhu", name:"上大新復健科診所", region:"north", city:"桃園市", district:"蘆竹區", address:"桃園市蘆竹區桃園街12、16、18、20、22號", phone:"03-322-5707", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"bade-rehab", name:"復健診所（八德）", region:"north", city:"桃園市", district:"八德區", address:"桃園市八德區介壽路二段135號5樓", phone:"03-364-3470", url:"", services:"物理、職能、語言治療、感覺統合", dedicated:false},
  {id:"tygh-xinwu", name:"衛生福利部桃園醫院新屋分院", region:"north", city:"桃園市", district:"新屋區", address:"桃園市新屋區新福二路6號", phone:"03-497-1989#5161", url:"https://www.tygh.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"youming-xinwu", name:"佑明診所", region:"north", city:"桃園市", district:"新屋區", address:"桃園市新屋區三民路518號1至3樓", phone:"03-497-0568", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"minsheng-longtan", name:"敏盛綜合醫院龍潭分院", region:"north", city:"桃園市", district:"龍潭區", address:"桃園市龍潭區中豐路168號", phone:"03-479-4151#1120", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ndmctyg-longtan", name:"國軍桃園總醫院附設民眾診療服務處", region:"north", city:"桃園市", district:"龍潭區", address:"桃園市龍潭區中興路168號", phone:"03-480-7777#325142", url:"", services:"物理、職能、語言治療、感覺統合", dedicated:false},

  /* ----- 北區 · 新竹縣 ----- */
  {id:"lovetalk-zhubei", name:"樂語語言治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市光明六路東二段112號", phone:"", url:"https://www.lovetalkclinic.com", services:"語言治療", dedicated:true},
  {id:"hemu-zhubei", name:"和沐復健專科診所（新竹院區）", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市復興二路13號", phone:"03-667-0052", url:"https://www.homeclinic213.com.tw", services:"兒童早療、語言治療", dedicated:false},
  {id:"jialeshui-zhubei", name:"佳樂水語言治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市嘉興路124號", phone:"03-667-3963", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"binbi-zhubei", name:"苂比語言治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市嘉豐六路二段170號", phone:"03-550-2195", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"sibi-zhubei", name:"思比語言治療所（竹北）", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市六家一路一段126號2樓之二", phone:"0963-510158", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"daxin-zhubei", name:"達心聯合治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市勝利六街198號", phone:"0967-111781", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinxin-zhubei", name:"忻心聯合治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市勝利十二街98號1、2樓", phone:"0965-722061", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ruizhimeng-zhubei", name:"瑞之盟竹塹居家語言治療所", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市鹿場里自強七街33號5樓518室", phone:"0907-010671", url:"", services:"居家語言治療（長照到府）", dedicated:true},
  {id:"tungs-zhubei", name:"東元綜合醫院", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市縣政二路69號", phone:"03-552-7000", url:"https://www.tyh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"cmu-zhubei", name:"中國醫藥大學新竹附設醫院", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市興隆路一段199號", phone:"03-558-0558", url:"https://www.cmuhch.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"ntuh-biomed-zhubei", name:"臺大醫院生醫園區分院", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市生醫路一段2號", phone:"03-658-0833", url:"https://www.hch.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"xinren-zhubei", name:"竹北新仁醫院", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市博愛街331號", phone:"03-558-9955", url:"", services:"復健科語言治療", dedicated:false},
  {id:"ntuh-zhudong", name:"臺大醫院竹東分院", region:"north", city:"新竹縣", district:"竹東鎮", address:"新竹縣竹東鎮至善路52號", phone:"03-594-3248", url:"https://www.hch.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"vghtpe-zhudong", name:"臺北榮民總醫院新竹分院", region:"north", city:"新竹縣", district:"竹東鎮", address:"新竹縣竹東鎮中豐路一段81號", phone:"03-596-2134", url:"https://www.cdvh.vghtpe.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"renci-hukou", name:"天主教仁慈醫院", region:"north", city:"新竹縣", district:"湖口鄉", address:"新竹縣湖口鄉忠孝路29號", phone:"03-599-0790", url:"https://www.rch.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"yanhan-hukou", name:"彥涵復健科診所", region:"north", city:"新竹縣", district:"湖口鄉", address:"新竹縣湖口鄉中山路二段50巷38號", phone:"03-590-7666", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shikang-zhubei", name:"適康復健科診所（竹北）", region:"north", city:"新竹縣", district:"竹北市", address:"新竹縣竹北市勝利五路177號", phone:"03-667-2868", url:"", services:"物理、職能、語言治療", dedicated:false},

  /* ===================== 中區 ===================== */
  {id:"yuele-taichung-west", name:"悅樂語言治療所", region:"central", city:"臺中市", district:"南區", address:"臺中市南區復興路三段367號", phone:"04-2372-8468", url:"https://www.facebook.com/stprogress", services:"兒童早療、成人長照語言治療", dedicated:true},
  {id:"rumu-taichung-xitun", name:"如沐語言治療所", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區安和三街111號1樓", phone:"0986-617275", url:"https://www.rumuspeech.com", services:"兒童語言治療", dedicated:true},
  {id:"zhen-speech-dajia", name:"真語言治療所", region:"central", city:"臺中市", district:"大甲區", address:"臺中市大甲區中山路一段887號1樓", phone:"0963-147525", url:"", services:"語言治療", dedicated:true},
  {id:"haokang-taichung-beitun", name:"好康復健科診所", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區中清路二段901號", phone:"04-2426-1995", url:"https://www.hk901.com.tw", services:"物理、職能、語言治療、發展遲緩評估", dedicated:false},
  {id:"howtalk-taichung-east", name:"台中好好語言治療所", region:"central", city:"臺中市", district:"東區", address:"臺中市東區樂業路233號1樓", phone:"0905-803663", url:"https://www.howtalk.com.tw", services:"兒童／成人語言治療、構音治療", dedicated:true},
  {id:"brilliant-taichung-nantun", name:"高明台中復健科診所", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區大業路228、230號", phone:"04-2328-0608", url:"https://www.brilliant-clinic.com.tw", services:"兒童復健、語言治療、構音障礙治療", dedicated:false},
  {id:"cmuch-taichung-north", name:"中國醫藥大學兒童醫院", region:"central", city:"臺中市", district:"北區", address:"臺中市北區學士路95號", phone:"04-2205-2121", url:"https://cmuch.org.tw", services:"兒童復健、語言治療", dedicated:false},
  {id:"vghtc-taichung-xitun", name:"臺中榮民總醫院", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區臺灣大道四段1650號", phone:"04-2359-2525", url:"https://www.vghtc.gov.tw", services:"復健醫學部語言治療", dedicated:false},
  {id:"wetalk-beitun", name:"葳語語言治療所", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區松竹五路二段59號", phone:"04-2436-0152", url:"https://www.wetalkst.com", services:"兒童／成人語言治療、構音、口吃、吞嚥（採預約自費）", dedicated:true},
  {id:"xinyu-dali", name:"心語語言治療所", region:"central", city:"臺中市", district:"大里區", address:"臺中市大里區塗城路148-1號", phone:"0932-953774", url:"", services:"語言治療", dedicated:true},
  {id:"yuhui-taiping", name:"語輝語言治療所", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區建和路一段22巷19號1樓", phone:"0963-420682", url:"", services:"語言治療、居家服務", dedicated:true},
  {id:"xingyuanshu-taiping", name:"星願樹語言治療所", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區育才路436號", phone:"04-2391-0907", url:"", services:"語言治療", dedicated:true},
  {id:"yupei-fengyuan", name:"語沛語言治療所", region:"central", city:"臺中市", district:"豐原區", address:"臺中市豐原區綠山二街158號", phone:"04-2515-5180", url:"", services:"語言治療", dedicated:true},
  {id:"wlsh-wuri", name:"烏日林新醫院", region:"central", city:"臺中市", district:"烏日區", address:"臺中市烏日區榮和路168號", phone:"04-2338-8766", url:"https://wlshosp.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"baobei-shalu", name:"寶貝語言治療所", region:"central", city:"臺中市", district:"沙鹿區", address:"臺中市沙鹿區中山路378巷8號", phone:"04-2662-5085", url:"", services:"語言治療、認知學習、音樂療育", dedicated:true},
  {id:"hetian-west", name:"核甜語言治療所", region:"central", city:"臺中市", district:"西區", address:"臺中市西區民生路523號", phone:"0928-153389", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"hanlaoshi-north", name:"韓老師語言治療所", region:"central", city:"臺中市", district:"北區", address:"臺中市北區興進路207號1、2樓", phone:"04-2233-9412", url:"", services:"語言治療、認知學習（自費）", dedicated:true},
  {id:"muen-xitun", name:"沐恩語言治療所", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區福順路255巷18號", phone:"0909-709988", url:"", services:"語言治療、認知學習（自費）", dedicated:true},
  {id:"shangen-xitun", name:"上恩語言治療所", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區西屯路二段297-8巷12弄32號", phone:"04-2708-8036", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"shiti-beitun", name:"示緹語言治療所", region:"central", city:"臺中市", district:"潭子區", address:"臺中市潭子區中興路98號1樓", phone:"04-2422-7687", url:"", services:"語言治療、認知學習（自費）", dedicated:true},
  {id:"yuyao-beitun", name:"語曜語言治療所", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區北屯路428號之1", phone:"04-2247-6627", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"liangliang-nantun", name:"亮亮語言治療所", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區大進街30號", phone:"0966-538158", url:"", services:"語言治療、認知學習（自費）", dedicated:true},
  {id:"tuoqi-nantun", name:"託奇語言治療所", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區河南路四段422號", phone:"0966-088335", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"dagang-shalu", name:"大剛語言治療所", region:"central", city:"臺中市", district:"沙鹿區", address:"臺中市沙鹿區北勢東路750號2樓", phone:"04-2632-5958", url:"", services:"語言治療、認知治療（自費）", dedicated:true},
  {id:"youyu-tanzi", name:"優語語言治療所", region:"central", city:"臺中市", district:"潭子區", address:"臺中市潭子區福潭路531號1樓", phone:"0979-321623", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"guansheng-daya", name:"冠聲語言治療所", region:"central", city:"臺中市", district:"大雅區", address:"臺中市大雅區中清東路258號1樓", phone:"04-2565-0728", url:"", services:"語言治療", dedicated:true},
  {id:"jingying-east", name:"精英語言治療所", region:"central", city:"臺中市", district:"東區", address:"臺中市東區精武東路13號", phone:"04-2215-5112", url:"", services:"語言治療", dedicated:true},
  {id:"tongyanleyu-south", name:"童言樂語語言治療所", region:"central", city:"臺中市", district:"南區", address:"臺中市南區德祥街67巷27號", phone:"0963-513128", url:"", services:"語言治療", dedicated:true},
  {id:"tongxin-north", name:"童心語言治療所", region:"central", city:"臺中市", district:"北區", address:"臺中市北區三民路三段313號5樓之2", phone:"04-2233-3727", url:"", services:"語言治療", dedicated:true},
  {id:"sunsoda-north", name:"陽光汽水語言治療所", region:"central", city:"臺中市", district:"北區", address:"臺中市北區漢口路五段100之4號5樓", phone:"0911-969480", url:"", services:"語言治療、居家服務", dedicated:true},
  {id:"peiyu-beitun", name:"沛語語言治療所", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區瀋陽路三段293號1樓", phone:"04-2243-0868", url:"", services:"語言治療", dedicated:true},
  {id:"xinqiushuo-beitun", name:"心球說語言治療所", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區太原路三段1198號1樓", phone:"0917-068439", url:"", services:"語言治療", dedicated:true},
  {id:"tuoqi-daye-nantun", name:"託奇大業語言治療所", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區大業路573號", phone:"0983-600958", url:"", services:"語言治療", dedicated:true},
  {id:"yiliemaizi-nantun", name:"一粒麥子語言治療所", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區永春東路800號2樓", phone:"0919-023117", url:"", services:"語言治療", dedicated:true},
  {id:"siguoyu-dali", name:"思果語語言治療所", region:"central", city:"臺中市", district:"大里區", address:"臺中市大里區新南路69號", phone:"0972-372026", url:"", services:"語言治療", dedicated:true},
  {id:"yinghuochong-wufeng", name:"螢火蟲居家語言治療所", region:"central", city:"臺中市", district:"霧峰區", address:"臺中市霧峰區中正路648之3號1樓", phone:"0912-233076", url:"", services:"語言治療、居家服務", dedicated:true},
  {id:"quwan-dongshi", name:"趣玩語言治療所", region:"central", city:"臺中市", district:"東勢區", address:"臺中市東勢區中山路28號3樓", phone:"04-3611-1686", url:"", services:"語言治療", dedicated:true},
  {id:"zhongzi-shalu", name:"種子語言治療所", region:"central", city:"臺中市", district:"沙鹿區", address:"臺中市沙鹿區鹿寮里中山路494之3號", phone:"04-2665-5580", url:"", services:"語言治療", dedicated:true},
  {id:"dazhi-wuqi", name:"大稚語言治療所", region:"central", city:"臺中市", district:"梧棲區", address:"臺中市梧棲區大智路一段525號3樓", phone:"04-2656-7568", url:"", services:"語言治療", dedicated:true},
  {id:"yuqiling-qingshui", name:"語其聆語言治療所", region:"central", city:"臺中市", district:"清水區", address:"臺中市清水區中清路九段300號", phone:"0911-719138", url:"", services:"語言治療", dedicated:true},
  // 臺中市醫院（語言治療單位）
  {id:"jahcm-taichung-central", name:"台中仁愛醫院", region:"central", city:"臺中市", district:"中區", address:"臺中市中區柳川東路三段36號", phone:"04-2225-5450", url:"https://www.jah.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"taisin-east", name:"台新醫院", region:"central", city:"臺中市", district:"東區", address:"臺中市東區振興路441號", phone:"04-2213-9966", url:"", services:"復健科語言治療", dedicated:false},
  {id:"cmuh-east", name:"中國醫藥大學附設醫院臺中東區分院", region:"central", city:"臺中市", district:"東區", address:"臺中市東區自由路三段296號", phone:"04-2212-1058", url:"https://www.cmuh.cmu.edu.tw", services:"復健科語言治療", dedicated:false},
  {id:"csmu-south", name:"中山醫學大學附設醫院", region:"central", city:"臺中市", district:"南區", address:"臺中市南區建國北路一段110號", phone:"04-2473-9595", url:"https://www.csh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"csmu-zhongxing-south", name:"中山醫學大學附設醫院中興分院", region:"central", city:"臺中市", district:"南區", address:"臺中市南區復興路二段11號", phone:"04-2262-1652", url:"https://www.csh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"taic-west", name:"衛生福利部臺中醫院", region:"central", city:"臺中市", district:"西區", address:"臺中市西區三民路一段199號", phone:"04-2229-4411", url:"https://www.taic.mohw.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"taan-shuangshi-north", name:"臺安醫院雙十分院", region:"central", city:"臺中市", district:"北區", address:"臺中市北區雙十路二段29號", phone:"04-2226-8990", url:"", services:"復健科語言治療", dedicated:false},
  {id:"afmc-zhongqing-north", name:"國軍臺中總醫院中清分院", region:"central", city:"臺中市", district:"北區", address:"臺中市北區忠明路500號", phone:"04-2203-3178", url:"", services:"復健科語言治療", dedicated:false},
  {id:"cmuh-north", name:"中國醫藥大學附設醫院", region:"central", city:"臺中市", district:"北區", address:"臺中市北區育德路2號", phone:"04-2205-2121", url:"https://www.cmuh.cmu.edu.tw", services:"復健科語言治療", dedicated:false},
  {id:"tcsenior-beitun", name:"臺中市立老人復健綜合醫院", region:"central", city:"臺中市", district:"北屯區", address:"臺中市北屯區太原路三段1141號", phone:"04-2437-5252", url:"", services:"復健科語言治療", dedicated:false},
  {id:"ccgh-zhonggang-xitun", name:"澄清綜合醫院中港分院", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區台灣大道四段966號", phone:"04-2463-2000", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"ccgh-rehab-xitun", name:"澄清復健醫院", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區敬德街8-1號", phone:"04-2461-2366#81121", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"ccgh-child-xitun", name:"澄清醫院中港分院兒童發展中心", region:"central", city:"臺中市", district:"西屯區", address:"臺中市西屯區敬德街8號B1", phone:"04-2461-4546#88879", url:"https://www.ccgh.com.tw", services:"兒童發展評估、語言治療", dedicated:false},
  {id:"lshosp-nantun", name:"林新醫院", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區惠中路三段36號", phone:"04-2258-6688", url:"https://www.lshosp.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"zhengde-nantun", name:"佛教正德醫院", region:"central", city:"臺中市", district:"南屯區", address:"臺中市南屯區文心南五路三段100號", phone:"04-3702-6588", url:"", services:"復健科語言治療", dedicated:false},
  {id:"xiande-taiping", name:"賢德醫院", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區宜昌路420號", phone:"04-2273-2551", url:"", services:"復健科語言治療", dedicated:false},
  {id:"changan-taiping", name:"長安醫院", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區永平路一段9號", phone:"04-3611-3611", url:"https://www.cahospital.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"xintaiping-ccgh-taiping", name:"新太平澄清醫院", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區中興路100號", phone:"04-2278-9900", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"afmc-taiping", name:"國軍臺中總醫院", region:"central", city:"臺中市", district:"太平區", address:"臺中市太平區中山路二段348號", phone:"04-2393-4191", url:"", services:"復健科語言治療", dedicated:false},
  {id:"jah-dali", name:"大里仁愛醫院", region:"central", city:"臺中市", district:"大里區", address:"臺中市大里區東榮路483號", phone:"04-2481-9900", url:"https://www.jah.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"wufeng-ccgh-dali", name:"霧峰澄清醫院", region:"central", city:"臺中市", district:"大里區", address:"臺中市大里區成功路55號", phone:"04-2492-2000", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"daming-eye-dali", name:"達明眼科醫院", region:"central", city:"臺中市", district:"大里區", address:"臺中市大里區中興路二段490號", phone:"04-2485-1437", url:"", services:"復健科語言治療", dedicated:false},
  {id:"auh-wufeng", name:"亞洲大學附屬醫院", region:"central", city:"臺中市", district:"霧峰區", address:"臺中市霧峰區福新路222號", phone:"04-3706-1668", url:"https://www.auh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"bentang-ccgh-wufeng", name:"本堂澄清醫院", region:"central", city:"臺中市", district:"霧峰區", address:"臺中市霧峰區中正路718號", phone:"04-2339-0000", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"wuri-ccgh", name:"烏日澄清醫院", region:"central", city:"臺中市", district:"烏日區", address:"臺中市烏日區光明路419號", phone:"04-2337-6232", url:"https://www.ccgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"fyh-fengyuan", name:"衛生福利部豐原醫院", region:"central", city:"臺中市", district:"豐原區", address:"臺中市豐原區安康路100號", phone:"04-2527-1180", url:"https://www.fyh.mohw.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"huisheng-fengyuan", name:"惠盛醫院", region:"central", city:"臺中市", district:"豐原區", address:"臺中市豐原區中正路268號", phone:"04-2522-9100", url:"", services:"復健科語言治療", dedicated:false},
  {id:"tctzuchi-tanzi", name:"台中慈濟醫院", region:"central", city:"臺中市", district:"潭子區", address:"臺中市潭子區豐興路一段88號", phone:"04-3606-0666", url:"https://taichung.tzuchi.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"qingquan-daya", name:"清泉醫院", region:"central", city:"臺中市", district:"大雅區", address:"臺中市大雅區雅潭路四段80號", phone:"04-2560-5600", url:"", services:"復健科語言治療", dedicated:false},
  {id:"sltung-shalu", name:"童綜合醫院", region:"central", city:"臺中市", district:"沙鹿區", address:"臺中市沙鹿區成功西街8號", phone:"04-2662-6161", url:"https://www.sltung.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"ktgh-shalu", name:"光田綜合醫院", region:"central", city:"臺中市", district:"沙鹿區", address:"臺中市沙鹿區沙田路117號", phone:"04-2662-5111", url:"https://www.ktgh.com.tw", services:"復健科語言治療", dedicated:false},
  {id:"lee-dajia", name:"大甲李綜合醫院", region:"central", city:"臺中市", district:"大甲區", address:"臺中市大甲區八德街2號", phone:"04-2686-2288", url:"https://www.lee.com.tw", services:"復健科語言治療", dedicated:false},
  // 彰化縣
  {id:"cch-changhua", name:"彰化基督教醫院", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市南校街135號", phone:"04-722-5132", url:"https://www.cch.org.tw", services:"復健科語言治療、兒童發展評估", dedicated:false},
  {id:"leshuo-changhua", name:"樂說語言治療所", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市長順街43巷22號1-3樓", phone:"04-7201590", url:"", services:"語言治療（採預約制）", dedicated:true},
  {id:"ylchristian-yuanlin", name:"員林基督教醫院", region:"central", city:"彰化縣", district:"員林市", address:"彰化縣員林市莒光路456號", phone:"04-838-3900", url:"https://www.cch.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"oule-changhua", name:"歐樂語言治療所", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市大埔路682巷1號", phone:"0918-960660", url:"", services:"語言治療", dedicated:true},
  {id:"sanhe-changhua", name:"三和語言治療所（附設聽力部門）", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市大埔路641號", phone:"04-7112591", url:"", services:"語言治療、聽力檢查", dedicated:true},
  {id:"baobei-changhua", name:"寶貝語言治療所", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市彰美路一段132巷83號1樓", phone:"04-7230285", url:"", services:"語言、職能、物理治療、音樂療育", dedicated:true},
  {id:"xinqing-changhua", name:"彰化縣心晴社會福利發展協會", region:"central", city:"彰化縣", district:"彰化市", address:"彰化縣彰化市永安東街23號", phone:"0983-253321", url:"", services:"職能、語言治療、學前教育", dedicated:false},
  {id:"xingyu-yuanlin", name:"杏宇語言治療所", region:"central", city:"彰化縣", district:"員林市", address:"彰化縣員林市中山路二段121號1樓", phone:"04-8390709", url:"", services:"語言治療", dedicated:true},
  {id:"yuanrong-yuanlin", name:"員榮醫院", region:"central", city:"彰化縣", district:"員林市", address:"彰化縣員林市莒光路359號", phone:"04-8383995", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yushun-yuanlin", name:"郁順復健科診所", region:"central", city:"彰化縣", district:"員林市", address:"彰化縣員林市靜修東路36號", phone:"04-8333567", url:"", services:"物理、職能、語言治療、音樂療育", dedicated:false},
  {id:"hope-yuanlin", name:"彰化縣私立希望社會福利慈善事業基金會", region:"central", city:"彰化縣", district:"員林市", address:"彰化縣員林市興隆街108號3樓", phone:"04-8316668", url:"", services:"物理、職能、語言治療、學前教育", dedicated:false},
  // 南投縣
  {id:"lepeng-nantou", name:"樂朋語言治療所", region:"central", city:"南投縣", district:"南投市", address:"南投縣南投市大同南街49號", phone:"049-222-5555", url:"", services:"語言治療", dedicated:true},
  {id:"nantou-hosp", name:"衛生福利部南投醫院", region:"central", city:"南投縣", district:"南投市", address:"南投縣南投市復興路478號", phone:"049-223-1150", url:"", services:"復健科語言治療", dedicated:false},
  {id:"puli-christian-nantou", name:"埔里基督教醫院", region:"central", city:"南投縣", district:"埔里鎮", address:"南投縣埔里鎮鐵山路1號", phone:"049-291-2151", url:"https://www.pch.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"vghtc-puli", name:"臺中榮民總醫院埔里分院", region:"central", city:"南投縣", district:"埔里鎮", address:"南投縣埔里鎮中山路三段339號", phone:"049-291-6041", url:"https://www.pulivh.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"weiling-caotun", name:"唯聆語言心理聯合治療所", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮仁愛街270號", phone:"0958-797012", url:"https://www.willingtotherapy.com", services:"語言治療、心理治療（採預約制）", dedicated:true},
  {id:"feixiang-caotun", name:"飛翔語言治療所", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮太平路一段325號", phone:"049-231-7979", url:"", services:"語言、認知治療（自費）", dedicated:true},
  {id:"yuyang-yuchi", name:"語揚語言治療所", region:"central", city:"南投縣", district:"魚池鄉", address:"南投縣魚池鄉魚池村秀水巷20-12號", phone:"0919-736397", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"shengmingshu-nantou", name:"生命樹職能治療所", region:"central", city:"南投縣", district:"南投市", address:"南投縣南投市文化南路106號1樓", phone:"0958-372049", url:"", services:"職能、語言、物理治療（自費）", dedicated:false},
  {id:"huihe-caotun", name:"惠和醫院", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮平等街140號", phone:"049-232-1188", url:"", services:"職能、物理、語言治療", dedicated:false},
  {id:"youmin-caotun", name:"佑民醫院", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮太平路一段200號", phone:"049-235-8151", url:"", services:"職能、物理、語言治療", dedicated:false},
  {id:"qunhe-caotun", name:"群和診所", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮新豐路728巷36號", phone:"049-235-3197", url:"", services:"職能、語言治療", dedicated:false},
  {id:"anxin-caotun", name:"安心復健科診所", region:"central", city:"南投縣", district:"草屯鎮", address:"南投縣草屯鎮中興路138號1-2樓", phone:"049-233-3874", url:"", services:"職能、物理、語言治療", dedicated:false},
  {id:"nantou-zhongxing", name:"衛生福利部南投醫院中興院區", region:"central", city:"南投縣", district:"南投市", address:"南投縣南投市環山路57號", phone:"049-233-9165", url:"https://www.pntn.mohw.gov.tw", services:"職能、物理、語言治療", dedicated:false},
  {id:"ntcmh-nantou", name:"南投基督教醫院", region:"central", city:"南投縣", district:"南投市", address:"南投縣南投市中興路870號", phone:"049-222-5595", url:"", services:"職能、物理、語言治療", dedicated:false},
  {id:"chushang-zhushan", name:"竹山秀傳醫院", region:"central", city:"南投縣", district:"竹山鎮", address:"南投縣竹山鎮集山路二段75號", phone:"049-262-4266", url:"", services:"職能、物理、語言、心理治療", dedicated:false},
  {id:"donghua-zhushan", name:"東華醫院", region:"central", city:"南投縣", district:"竹山鎮", address:"南投縣竹山鎮集山路三段272巷16號", phone:"049-265-8949", url:"", services:"職能、物理、語言治療", dedicated:false},
  // 雲林縣
  {id:"ntuh-yunlin-douliu", name:"臺大醫院雲林分院（斗六院區）", region:"central", city:"雲林縣", district:"斗六市", address:"雲林縣斗六市雲林路二段579號", phone:"05-532-3911", url:"https://www.ylh.gov.tw", services:"復健科語言治療、早期療育", dedicated:false},
  {id:"ntuh-yunlin-huwei", name:"臺大醫院雲林分院（虎尾院區）", region:"central", city:"雲林縣", district:"虎尾鎮", address:"雲林縣虎尾鎮學府路95號", phone:"05-633-0002", url:"https://www.ylh.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"weiyi-douliu", name:"唯一語言治療所", region:"central", city:"雲林縣", district:"斗六市", address:"雲林縣斗六市永興路68號1樓", phone:"0910-980987", url:"", services:"語言治療（需提前預約）", dedicated:true},
  {id:"zhenling-huwei", name:"媜聆之心語言治療所", region:"central", city:"雲林縣", district:"虎尾鎮", address:"雲林縣虎尾鎮立德路133號", phone:"0916-931657", url:"", services:"語言治療", dedicated:true},
  {id:"aizhen-huwei", name:"艾蓁語言治療所", region:"central", city:"雲林縣", district:"虎尾鎮", address:"雲林縣虎尾鎮虎興路二段256號", phone:"", url:"", services:"語言治療（LINE 預約 @654tgxlu）", dedicated:true},
  {id:"josephhosp-huwei", name:"天主教若瑟醫院", region:"central", city:"雲林縣", district:"虎尾鎮", address:"雲林縣虎尾鎮新生路74號", phone:"05-633-7333", url:"https://www.stjoh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"ycmh-xiluo", name:"雲林基督教醫院", region:"central", city:"雲林縣", district:"西螺鎮", address:"雲林縣西螺鎮民生路1號", phone:"05-587-1111", url:"", services:"復健科語言治療", dedicated:false},
  {id:"cmu-beigang", name:"中國醫藥大學北港附設醫院", region:"central", city:"雲林縣", district:"北港鎮", address:"雲林縣北港鎮新德路123號", phone:"05-783-7901", url:"", services:"復健科語言治療", dedicated:false},
  {id:"yuanben-douliu", name:"原本中山復健科診所", region:"central", city:"雲林縣", district:"斗六市", address:"雲林縣斗六市中山路92-1號", phone:"05-536-0879", url:"", services:"復健科語言治療", dedicated:false},
  {id:"huweitaijin-huwei", name:"虎尾台金復健診所", region:"central", city:"雲林縣", district:"虎尾鎮", address:"雲林縣虎尾鎮林森路一段412號", phone:"05-636-6111", url:"", services:"復健科語言治療", dedicated:false},
  {id:"nanchang-dounan", name:"南昌診所", region:"central", city:"雲林縣", district:"斗南鎮", address:"雲林縣斗南鎮五福路56號", phone:"05-597-8079", url:"", services:"復健科語言治療", dedicated:false},
  {id:"yuanhe-mailiao", name:"苑禾耳鼻喉科診所", region:"central", city:"雲林縣", district:"麥寮鄉", address:"雲林縣麥寮鄉新興路16號2樓", phone:"05-693-0099", url:"", services:"語言治療（麥寮台金聯合診所內）", dedicated:false},
  // 苗栗縣
  {id:"dachien-miaoli", name:"大千綜合醫院", region:"central", city:"苗栗縣", district:"苗栗市", address:"苗栗縣苗栗市恭敬路36號", phone:"037-357-125", url:"https://www.dachien.com.tw", services:"復健科語言治療、兒童發展聯合評估", dedicated:false},
  {id:"weigong-miaoli", name:"為恭醫院", region:"central", city:"苗栗縣", district:"頭份市", address:"苗栗縣頭份市信義路128號", phone:"037-676-811", url:"", services:"復健科語言治療", dedicated:false},
  {id:"shengyang-toufen", name:"聲揚聯合治療所", region:"central", city:"苗栗縣", district:"頭份市", address:"苗栗縣頭份市維新路26號", phone:"0910-348480", url:"", services:"語言治療、職能治療（自費）", dedicated:false},

  /* ===================== 南區 ===================== */
  {id:"bridges-tainan-yongkang", name:"欣橋語言治療所", region:"south", city:"臺南市", district:"永康區", address:"臺南市永康區東橋六街85號", phone:"06-302-2805", url:"https://www.bridges-clinic.com/speech-language", services:"兒童／成人語言治療、吞嚥治療、口吃治療", dedicated:true},
  {id:"kangchun-yongkang", name:"康群復健科診所", region:"south", city:"臺南市", district:"永康區", address:"臺南市永康區復國一路236號", phone:"06-313-8899", url:"https://www.kangchun.com.tw", services:"兒童早療、語言治療", dedicated:false},
  {id:"buabu-union-kaohsiung-zuoying", name:"步步聯合治療所", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區安吉街449號", phone:"07-550-8682", url:"", services:"以家庭為中心的兒童語言治療", dedicated:true},
  {id:"changhong-kaohsiung-nanzi", name:"昶虹語言治療所", region:"south", city:"高雄市", district:"楠梓區", address:"高雄市楠梓區興楠路59號", phone:"", url:"", services:"語言治療", dedicated:true},
  {id:"aishuo-kaohsiung-lingya", name:"愛說語言治療所", region:"south", city:"高雄市", district:"苓雅區", address:"高雄市苓雅區建民路53號", phone:"", url:"", services:"語言治療", dedicated:true},
  {id:"vghks-kaohsiung-zuoying", name:"高雄榮民總醫院", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區大中一路386號", phone:"07-342-2121#74200", url:"https://org.vghks.gov.tw/reh/", services:"語言治療（復健醫學部）", dedicated:false},
  {id:"shenggong-kaohsiung-lingya", name:"天主教聖功醫院", region:"south", city:"高雄市", district:"苓雅區", address:"高雄市苓雅區建國一路352號", phone:"07-223-8153", url:"", services:"語言、吞嚥、言語治療、兒童聯合評估", dedicated:false},
  {id:"fongshan-hosp-kaohsiung", name:"高雄長庚（鳳山）醫院", region:"south", city:"高雄市", district:"鳳山區", address:"高雄市鳳山區經武路42之1號5樓", phone:"07-741-8151#5401", url:"", services:"語言治療", dedicated:false},
  {id:"ncku-tainan-north", name:"國立成功大學醫學院附設醫院", region:"south", city:"臺南市", district:"北區", address:"臺南市北區勝利路138號", phone:"06-235-3535", url:"https://www.hosp.ncku.edu.tw", services:"復健部語言治療、兒童聯合評估", dedicated:false},
  {id:"chimei-tainan-yongkang", name:"奇美醫院（永康）", region:"south", city:"臺南市", district:"永康區", address:"臺南市永康區中華路901號", phone:"06-281-2811", url:"https://www.chimei.org.tw", services:"物理、職能、語言治療、兒童聯合評估", dedicated:false},
  {id:"chimei-liuying", name:"柳營奇美醫院", region:"south", city:"臺南市", district:"柳營區", address:"臺南市柳營區太康里太康201號", phone:"06-622-6999", url:"https://www.chimei.org.tw", services:"復健科語言治療（兒童與成人）", dedicated:false},
  {id:"chimei-jiali", name:"佳里奇美醫院", region:"south", city:"臺南市", district:"佳里區", address:"臺南市佳里區佳里興606號", phone:"06-726-3333", url:"https://www.chimei.org.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"tnhp-tainan-west", name:"衛生福利部臺南醫院", region:"south", city:"臺南市", district:"中西區", address:"臺南市中西區中山路125號", phone:"06-220-0055", url:"https://www.tnhp.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"jinan-tainan", name:"晉安復健科診所", region:"south", city:"臺南市", district:"東區", address:"臺南市東區崇善路670號", phone:"06-268-5296", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xuezejie-tainan", name:"薛澤杰復健科診所", region:"south", city:"臺南市", district:"東區", address:"臺南市東區東門路一段298號1樓", phone:"06-238-6150", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinlou-tainan", name:"臺南新樓醫院", region:"south", city:"臺南市", district:"東區", address:"臺南市東區東門路一段57號", phone:"06-274-8316", url:"https://www.sinlau.org.tw", services:"職能、物理、語言治療", dedicated:false},
  {id:"changxin-tainan", name:"長欣復健科診所", region:"south", city:"臺南市", district:"北區", address:"臺南市北區臨安路二段209號", phone:"06-258-9625", url:"", services:"語言、物理、職能治療", dedicated:false},
  {id:"chenzhicheng-tainan", name:"陳志誠耳鼻喉科醫院", region:"south", city:"臺南市", district:"北區", address:"臺南市北區公園路315之1號", phone:"06-221-0423", url:"", services:"語言治療", dedicated:false},
  {id:"yonghe-tainan", name:"永和醫院", region:"south", city:"臺南市", district:"中西區", address:"臺南市中西區府前路一段310號", phone:"06-223-1191#845", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"rencun-tainan", name:"仁村醫院", region:"south", city:"臺南市", district:"中西區", address:"臺南市中西區西門路一段486號", phone:"06-215-2607#291", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"zekang-tainan", name:"澤康復健診所", region:"south", city:"臺南市", district:"中西區", address:"臺南市中西區永華一街89號", phone:"06-299-2112", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"guo-tainan", name:"郭綜合醫院", region:"south", city:"臺南市", district:"中西區", address:"臺南市中西區民生路二段22號", phone:"06-222-1111#1262", url:"https://www.kuo-general.org.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"jinsheng-yongkang", name:"晉生醫院", region:"south", city:"臺南市", district:"永康區", address:"臺南市永康區中山南路902巷5號", phone:"06-233-0003", url:"", services:"語言治療", dedicated:false},
  {id:"renyi-rende", name:"仁義復健科診所", region:"south", city:"臺南市", district:"仁德區", address:"臺南市仁德區中正路二段330巷5號", phone:"06-249-6323", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"madou-xinlou", name:"麻豆新樓醫院", region:"south", city:"臺南市", district:"麻豆區", address:"臺南市麻豆區小埤里苓子林20號", phone:"06-570-2228#4170", url:"https://www.sinlau.org.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"kmuh-kaohsiung-sanmin", name:"高雄醫學大學附設中和紀念醫院", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區自由一路100號", phone:"07-312-1101", url:"https://www.kmuh.org.tw", services:"復健科語言治療組", dedicated:false},
  {id:"cgmh-kaohsiung-niaosong", name:"高雄長庚紀念醫院", region:"south", city:"高雄市", district:"鳥松區", address:"高雄市鳥松區大埤路123號", phone:"07-731-7123", url:"https://www.cgmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"hemu-kaohsiung", name:"和沐復健專科診所（高雄院區）", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區明華一路348號", phone:"07-550-7301", url:"https://www.homeclinic213.com.tw", services:"兒童早療、語言治療", dedicated:false},
  {id:"xiwang-sanmin", name:"曦望語言治療所", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區文濱路60號2樓", phone:"07-777-4649", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"edah-dachang-sanmin", name:"義大大昌醫院", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區大昌一路305號", phone:"07-559-9123#7536", url:"https://www.edah.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"qingzhang-sanmin", name:"青彰復健科診所", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區明誠一路192號", phone:"07-342-7966", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"xingao-sanmin", name:"新高醫院", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區莊敬路288號", phone:"07-390-9230", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"jianhong-sanmin", name:"建宏復健科診所", region:"south", city:"高雄市", district:"三民區", address:"高雄市三民區覺民路82號", phone:"07-381-1366", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"botian-zuoying", name:"博田國際醫院", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區博愛二路100號", phone:"07-556-2217", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yourong-zuoying", name:"佑榮復健科診所", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區左營大路2-60號", phone:"07-588-3380", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jiaren-zuoying", name:"嘉仁診所", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區翠華路609號", phone:"07-588-1977", url:"", services:"物理、語言治療", dedicated:false},
  {id:"deneng-zuoying", name:"德能診所", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區左營大路692號", phone:"07-585-7673", url:"", services:"物理、語言治療", dedicated:false},
  {id:"fuyin-zuoying", name:"福音復健科診所", region:"south", city:"高雄市", district:"左營區", address:"高雄市左營區新下街260號", phone:"07-550-7491", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ksmh-gushan", name:"高雄市立聯合醫院", region:"south", city:"高雄市", district:"鼓山區", address:"高雄市鼓山區中華一路976號", phone:"07-555-2565#2709", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jinghua-gushan", name:"精華診所", region:"south", city:"高雄市", district:"鼓山區", address:"高雄市鼓山區明倫路46號", phone:"07-550-4790", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"changyou-gushan", name:"長佑診所", region:"south", city:"高雄市", district:"鼓山區", address:"高雄市鼓山區裕誠路1580號", phone:"07-553-2356", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xinhua-xinxing", name:"新華醫院", region:"south", city:"高雄市", district:"新興區", address:"高雄市新興區七賢二路97號", phone:"07-287-6080#202", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xiaozhiwen-xinxing", name:"蕭志文醫院", region:"south", city:"高雄市", district:"新興區", address:"高雄市新興區七賢一路102號", phone:"07-224-0252#217", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jinan-xinxing", name:"晉安復健科診所", region:"south", city:"高雄市", district:"新興區", address:"高雄市新興區五福二路158號", phone:"07-241-6888", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"datong-qianjin", name:"高雄市立大同醫院", region:"south", city:"高雄市", district:"前金區", address:"高雄市前金區中華三路68號", phone:"07-291-1101#8347", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"shanglin-qianjin", name:"上琳醫院", region:"south", city:"高雄市", district:"前金區", address:"高雄市前金區自強一路67號", phone:"07-282-8668", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"minsheng-lingya", name:"高雄市立民生醫院", region:"south", city:"高雄市", district:"苓雅區", address:"高雄市苓雅區凱旋二路134號", phone:"07-751-1131#2005", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ruan-lingya", name:"阮綜合醫院", region:"south", city:"高雄市", district:"苓雅區", address:"高雄市苓雅區成功一路162號", phone:"07-335-1121#2278", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"dayi-lingya", name:"大益診所", region:"south", city:"高雄市", district:"苓雅區", address:"高雄市苓雅區同慶路60號", phone:"07-223-1670", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"anbo-qianzhen", name:"安柏鄰好中西醫聯合診所", region:"south", city:"高雄市", district:"前鎮區", address:"高雄市前鎮區民權二路180號2樓", phone:"07-335-0802", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"meizhong-qianzhen", name:"美忠復健科診所", region:"south", city:"高雄市", district:"前鎮區", address:"高雄市前鎮區翠亨北路547號", phone:"07-822-5558", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yichang-qianzhen", name:"易昌復健科診所", region:"south", city:"高雄市", district:"前鎮區", address:"高雄市前鎮區中華五路1011號", phone:"07-536-5808", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"ruixiang-qianzhen", name:"瑞祥醫院", region:"south", city:"高雄市", district:"前鎮區", address:"高雄市前鎮區班超路92號", phone:"07-771-7503", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"qijin-hosp", name:"高雄市立旗津醫院", region:"south", city:"高雄市", district:"旗津區", address:"高雄市旗津區旗港路33號", phone:"07-571-1188#1103", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"xiaogang-hosp", name:"高雄市立小港醫院", region:"south", city:"高雄市", district:"小港區", address:"高雄市小港區山明路482號", phone:"07-803-6783#3537", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"youchang-nanzi", name:"右昌聯合醫院", region:"south", city:"高雄市", district:"楠梓區", address:"高雄市楠梓區軍校路930號", phone:"07-364-3388#8201", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"huide-fengshan", name:"惠德醫院", region:"south", city:"高雄市", district:"鳳山區", address:"高雄市鳳山區福祥街81號", phone:"07-812-6000#1206", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"jiahuan-fengshan", name:"家歡復健專科診所", region:"south", city:"高雄市", district:"鳳山區", address:"高雄市鳳山區中山路74號1-2樓", phone:"07-719-0579", url:"", services:"物理、職能、語言治療（自費）", dedicated:false},
  {id:"xingaofeng-fengshan", name:"新高鳳醫院", region:"south", city:"高雄市", district:"鳳山區", address:"高雄市鳳山區光遠路360號", phone:"07-740-8650", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"wenherui-luzhu", name:"溫賀睿和醫院", region:"south", city:"高雄市", district:"路竹區", address:"高雄市路竹區延平路57號", phone:"07-696-5136#260", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"ndmcgs-gangshan", name:"國軍高雄總醫院岡山分院", region:"south", city:"高雄市", district:"岡山區", address:"高雄市岡山區大義二路1號", phone:"07-625-0919#6193", url:"", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"jiayu-gangshan", name:"佳語語言治療所", region:"south", city:"高雄市", district:"岡山區", address:"高雄市岡山區大義二路100號1樓", phone:"0987-529345", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"qiaohe-qiaotou", name:"橋禾診所", region:"south", city:"高雄市", district:"橋頭區", address:"高雄市橋頭區新東二街156號1樓", phone:"07-611-6521", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"edah-yanchao", name:"義大醫院", region:"south", city:"高雄市", district:"燕巢區", address:"高雄市燕巢區角宿里義大路1號", phone:"07-615-0011#2332", url:"https://www.edah.org.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"cishan-hosp", name:"衛生福利部旗山醫院", region:"south", city:"高雄市", district:"旗山區", address:"高雄市旗山區中學路60號", phone:"07-661-3811#1019", url:"https://www.csh.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"xizhou-cishan", name:"溪洲醫院", region:"south", city:"高雄市", district:"旗山區", address:"高雄市旗山區延平一路412號", phone:"07-662-1985", url:"", services:"物理、職能、語言治療", dedicated:false},
  // 嘉義市
  {id:"cych-chiayi", name:"嘉義基督教醫院", region:"south", city:"嘉義市", district:"東區", address:"嘉義市東區保健街100號", phone:"05-276-5041", url:"https://www.cych.org.tw", services:"復健科語言治療、兒童發展聯合評估", dedicated:false},
  {id:"stm-chiayi", name:"天主教聖馬爾定醫院", region:"south", city:"嘉義市", district:"東區", address:"嘉義市東區大雅路二段565號", phone:"05-275-6000", url:"https://www.stm.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"chiayi-hosp", name:"衛生福利部嘉義醫院", region:"south", city:"嘉義市", district:"西區", address:"嘉義市西區北港路312號", phone:"05-231-9090", url:"https://www.cyhp.mohw.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"cgmh-chiayi", name:"嘉義長庚紀念醫院", region:"south", city:"嘉義縣", district:"朴子市", address:"嘉義縣朴子市嘉朴路西段6號", phone:"05-362-1000", url:"https://www.cgmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"vghtc-chiayi", name:"臺中榮民總醫院嘉義分院", region:"south", city:"嘉義市", district:"西區", address:"嘉義市西區世賢路二段600號", phone:"05-235-9630#2801", url:"https://www.vhcy.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"ymhosp-chiayi", name:"嘉義陽明醫院", region:"south", city:"嘉義市", district:"東區", address:"嘉義市東區吳鳳北路252號", phone:"05-228-4567#7763", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"qingsheng-chiayi", name:"慶昇醫院", region:"south", city:"嘉義市", district:"西區", address:"嘉義市西區新榮路339號", phone:"05-222-9191#313", url:"", services:"物理、職能、語言治療（可夜間）", dedicated:false},
  {id:"boai-chiayi", name:"博愛復健科診所", region:"south", city:"嘉義市", district:"西區", address:"嘉義市西區興業西路136-118號", phone:"05-286-6600", url:"", services:"物理、職能、語言治療（可夜間）", dedicated:false},
  {id:"fuyin-chiayi", name:"福音聯合診所", region:"south", city:"嘉義市", district:"東區", address:"嘉義市東區吳鳳北路340號", phone:"05-278-2036", url:"", services:"語言治療", dedicated:false},
  {id:"hongpeikai-chiayi", name:"洪培凱耳鼻喉科診所", region:"south", city:"嘉義市", district:"西區", address:"嘉義市西區新民路632號1樓", phone:"05-286-6689", url:"", services:"構音矯正（語言治療，採預約制）", dedicated:false},
  {id:"pohotzu-chiayi", name:"衛生福利部朴子醫院", region:"south", city:"嘉義縣", district:"朴子市", address:"嘉義縣朴子市永和里42-50號", phone:"05-379-0600", url:"https://www.pjh.mohw.gov.tw", services:"復健科語言治療", dedicated:false},
  {id:"dalin-tzuchi", name:"佛教慈濟綜合醫院大林分院", region:"south", city:"嘉義縣", district:"大林鎮", address:"嘉義縣大林鎮民生路2號", phone:"05-264-8000", url:"https://dalin.tzuchi.com.tw", services:"復健科聽語中心（語言治療）", dedicated:false},
  // 屏東縣
  {id:"ptch-pingtung", name:"屏東基督教醫院", region:"south", city:"屏東縣", district:"屏東市", address:"屏東縣屏東市大連路60號", phone:"08-736-8686", url:"https://www.ptch.org.tw", services:"復健科語言治療、早期療育", dedicated:false},
  {id:"pth-pingtung", name:"衛生福利部屏東醫院", region:"south", city:"屏東縣", district:"屏東市", address:"屏東縣屏東市自由路270號", phone:"08-736-3011", url:"", services:"復健科語言治療", dedicated:false},
  {id:"ptvgh-pingtung", name:"屏東榮民總醫院", region:"south", city:"屏東縣", district:"屏東市", address:"屏東縣屏東市大湖路58巷15號", phone:"08-770-3115", url:"https://org.ptvgh.gov.tw", services:"復健科兒童語言治療", dedicated:false},
  {id:"yuenen-pingtung", name:"悅恩語言治療所", region:"south", city:"屏東縣", district:"屏東市", address:"屏東縣屏東市公園東路82-3號", phone:"08-722-0360", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"siweiluo-pingtung", name:"思維羅語言治療所", region:"south", city:"屏東縣", district:"屏東市", address:"屏東縣屏東市瑞光路二段350號", phone:"", url:"", services:"語言治療（LINE 預約 @796ddyli）", dedicated:true},
  // 澎湖縣
  {id:"tsgh-penghu", name:"三軍總醫院澎湖分院", region:"south", city:"澎湖縣", district:"馬公市", address:"澎湖縣馬公市前寮里90號", phone:"06-921-1116", url:"", services:"復健科語言治療", dedicated:false},
  // 金門縣
  {id:"huiyu-jinhu", name:"惠語語言治療所", region:"south", city:"金門縣", district:"金湖鎮", address:"金門縣金湖鎮山外里復興西路8之1號", phone:"082-330180", url:"", services:"語言治療", dedicated:true},

  /* ===================== 東區 ===================== */
  {id:"pohai-yilan-luodong", name:"羅東博愛醫院", region:"east", city:"宜蘭縣", district:"羅東鎮", address:"宜蘭縣羅東鎮南昌街83號", phone:"03-954-3131", url:"https://www.pohai.org.tw", services:"成人／兒童語言治療（復健科）", dedicated:false},
  {id:"smh-yilan-luodong", name:"羅東聖母醫院", region:"east", city:"宜蘭縣", district:"羅東鎮", address:"宜蘭縣羅東鎮中正南路160號", phone:"03-954-4106", url:"https://www.smh.org.tw", services:"語言治療（復健科）", dedicated:false},
  {id:"panliyun-yilan", name:"潘麗雲語言治療所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市宜興路一段75號2樓", phone:"03-935-4609", url:"", services:"語言治療", dedicated:true},
  {id:"heyue-yilan", name:"和悅語言治療所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市女中路三段66號4樓", phone:"03-935-1958", url:"", services:"語言治療", dedicated:true},
  {id:"yisheng-yilan", name:"宜昇復健科診所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市中山路二段307號", phone:"03-932-3000", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"taolebi-yilan", name:"桃樂比語言治療所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市泰山路85巷10號1樓", phone:"0900-772890", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"fuyou-yilan", name:"賦優聯合醫事機構語言治療所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市宜中路131號", phone:"03-932-9966", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"qingtian-luodong", name:"晴天語言治療所", region:"east", city:"宜蘭縣", district:"羅東鎮", address:"宜蘭縣羅東鎮純精路二段132號", phone:"03-957-7879", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"deyan-luodong", name:"得言語言治療所", region:"east", city:"宜蘭縣", district:"羅東鎮", address:"宜蘭縣羅東鎮樹人路13號1樓", phone:"03-955-1017", url:"", services:"語言治療（自費）", dedicated:true},
  {id:"ymu-yilan", name:"陽明交通大學附設醫院", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市新民路152號", phone:"03-932-5192", url:"https://www.ymuh.ym.edu.tw", services:"物理、職能、語言、心理治療", dedicated:false},
  {id:"pumen-yilan", name:"普門診所", region:"east", city:"宜蘭縣", district:"宜蘭市", address:"宜蘭縣宜蘭市神農路一段87號", phone:"03-932-7777", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"yuanshan-vh", name:"員山榮民醫院", region:"east", city:"宜蘭縣", district:"員山鄉", address:"宜蘭縣員山鄉榮光路386號", phone:"03-922-2141", url:"", services:"物理、職能、語言治療", dedicated:false},
  {id:"zaoliao-zhuangwei", name:"宜蘭縣早期療育復健中心", region:"east", city:"宜蘭縣", district:"壯圍鄉", address:"宜蘭縣壯圍鄉中央路二段290號", phone:"03-938-0670", url:"", services:"職能、語言治療", dedicated:false},
  {id:"jianshilin-luodong", name:"簡世霖復健科診所", region:"east", city:"宜蘭縣", district:"羅東鎮", address:"宜蘭縣羅東鎮倉前路77-7號", phone:"03-956-6619", url:"", services:"物理、語言治療", dedicated:false},
  {id:"tzuchi-hualien", name:"花蓮慈濟醫院", region:"east", city:"花蓮縣", district:"花蓮市", address:"花蓮縣花蓮市中央路三段707號", phone:"03-856-1825", url:"https://hlm.tzuchi.com.tw", services:"語言治療（復健醫學部）", dedicated:false},
  {id:"tch-taitung", name:"臺東基督教醫院", region:"east", city:"臺東縣", district:"臺東市", address:"臺東縣臺東市開封街350號", phone:"08-996-0888", url:"https://www.tch.org.tw", services:"兒童／成人語言治療、早期療育（復健治療部）", dedicated:false},
  {id:"mch-hualien", name:"門諾醫院", region:"east", city:"花蓮縣", district:"花蓮市", address:"花蓮縣花蓮市民權路44號", phone:"03-824-1234", url:"https://www.mch.org.tw", services:"復健科聽力語言治療", dedicated:false},
  {id:"hwln-hualien", name:"衛生福利部花蓮醫院", region:"east", city:"花蓮縣", district:"花蓮市", address:"花蓮縣花蓮市中正路600號", phone:"03-835-8141", url:"https://www.hwln.mohw.gov.tw", services:"物理、職能、語言治療", dedicated:false},
  {id:"ttmmh-taitung", name:"臺東馬偕紀念醫院", region:"east", city:"臺東縣", district:"臺東市", address:"臺東縣臺東市長沙街303巷1號", phone:"089-310-150", url:"https://ttw3.mmh.org.tw", services:"復健科語言治療", dedicated:false},
  {id:"tait-taitung", name:"衛生福利部臺東醫院", region:"east", city:"臺東縣", district:"臺東市", address:"臺東縣臺東市五權街1號", phone:"089-324-112", url:"https://www.tait.mohw.gov.tw", services:"復健科語言治療", dedicated:false}
];
